students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/urls.py
from django.urls import path, include, re_path
from .views import *
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView


app_name = "hotel"

urlpatterns = [
    path('rooms/', RoomListAPIView.as_view(), name='room_list'),
    path('clients/', ClientListAPIView.as_view(), name='client_list'),
    path('employees/', EmployeeListAPIView.as_view(), name='employee_list'),
    path('create_room/', RoomCreateView.as_view(), name='create_room'),
    path('clients_in_room/<int:room_number>/<start_date>/<end_date>/', ClientsInRoomView.as_view(),
         name='clients_in_room'),
    path('clients_in_room_form/', clients_in_room_form, name='clients_in_room_form'),
    path('clients_from_city/<str:city>/', ClientsFromCityView.as_view(), name='clients_from_city'),
    path('clients_from_city_form/', clients_from_city_form, name='clients_from_city_form'),
    path('cleaner_for_client_form/', cleaner_for_client_form, name='cleaner_for_client_form'),
    path('cleaner_info/<int:client_id>/<int:work_day>/', CleanerInfoView.as_view(), name='cleaner_info'),
    path('free_rooms_form/', free_rooms_for_date, name='free_rooms_form'),
    path('free_rooms/<str:check_in_date>/<str:check_out_date>/', FreeRoomsAPIView.as_view(), name='free_rooms'),
    path('clients_in_the_same_days_form/', clients_in_the_same_days, name='clients_in_the_same_days_form'),
    path('clients_in_same_days/<int:client_id>/<str:check_in_date>/<str:check_out_date>/',
         ClientsInSameDaysView.as_view(), name='clients_in_same_days'),
    path('v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('fire_employee/', fire_employee, name='fire_employee'),
    path('fire_employee/<int:pk>/', FireEmployeeView.as_view(), name='fire_employee_1'),
    path('update_employee_schedule/', update_employee_schedule, name='update_employee_schedule_form'),
    path('update_employee_schedule/<int:pk>/', UpdateEmployeeScheduleView.as_view(), name='update_employee_schedule'),
    path('check_in_client_form/', check_in_client, name='check_in'),
    path('check_in_client/<int:pk>/', CheckInClientView.as_view(), name='check_in_client'),
    path('quarterly_report_data/', quarterly_report, name='quarterly_report_data'),
    path('quarterly_report/<int:quarter>/<int:year>/', QuarterlyReportView.as_view(), name='quarterly_report'),
    path('', form_links, name='form_links'),
    path('user_bookings/<int:user_id>/', UserBookingsView.as_view(), name='user-bookings'),

    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('user', UserView.as_view()),
    path('logout', LogoutView.as_view()),

]

students/k33421/Afonina_Natalia/Lab_3/lab_3/lab_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('hotel.urls')),
    path('v1/drf-auth/', include('rest_framework.urls')),
]

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)

    REQUIRED_FIELDS = []


class Client(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    passport = models.CharField(max_length=15)
    from_city = models.CharField(max_length=20)
    bookings = models.ManyToManyField('Bookings', related_name='client_bookings', blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Floor(models.Model):
    floor = models.PositiveIntegerField()

    def __str__(self):
        return f'Floor {self.floor}'


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('SINGLE', 'Single Room'),
        ('DOUBLE', 'Double Room'),
        ('TRIPLE', 'Triple Room'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=6, choices=ROOM_CATEGORIES)
    cost = models.IntegerField()
    phone = models.CharField(max_length=15)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.number} {self.category} room'


class Bookings(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='user_bookings')
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()
    check_in_done = models.BooleanField(default=False, null=True, blank=True)
    check_out_done = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return f'{self.user} booked {self.room} from {self.check_in} to {self.check_out}'


class Employee(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class EmployeeSchedule(models.Model):
    DAYS_OF_WEEK = [
        ('Mon', 'Monday'),
        ('Tue', 'Tuesday'),
        ('Wed', 'Wednesday'),
        ('Thu', 'Thursday'),
        ('Fri', 'Friday'),
        ('Sat', 'Saturday'),
        ('Sun', 'Sunday'),
    ]
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    work_day = models.CharField(max_length=3, choices=DAYS_OF_WEEK)

    def __str__(self):
        return f"{self.employee} cleans {self.floor} on {self.work_day}s"


class RoomCleaningSchedule(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    employee = models.ForeignKey(EmployeeSchedule, on_delete=models.CASCADE)
    work_date = models.DateField()

    def __str__(self):
        return f"{self.employee} - {self.work_date}"

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/forms.py
from django import forms


class ClientsFromCityForm(forms.Form):
    city = forms.CharField(max_length=100, required=False)

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/views.py
from datetime import datetime

from django.db.models import Sum, Count
from django.db.models.functions import Coalesce
import jwt, datetime
from rest_framework.authentication import TokenAuthentication
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.views import *
from rest_framework.response import Response
from rest_framework import status, generics
from .models import *
from .serializers import *
from django.shortcuts import render, get_object_or_404


class RoomListAPIView(generics.ListAPIView):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    # permission_classes = (IsAuthenticated,)
    # authentication_classes = (TokenAuthentication, )


# class RoomListAPIView(APIView):
#     def get(self, request):
#         rooms = Room.objects.all()
#         serializer = RoomSerializer(rooms, many=True)
#         return Response(serializer.data)

class ClientListAPIView(generics.ListAPIView):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer


class EmployeeListAPIView(generics.ListCreateAPIView):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    permission_classes = (IsAdminUser,)


class RoomCreateView(generics.ListCreateAPIView):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer


# class RoomCreateView(APIView):
#     def get(self, request):
#         rooms = Room.objects.all()
#         serializer = RoomSerializer(rooms, many=True)
#         return Response(serializer.data)
#
#     def post(self, request):
#         serializer = RoomCreateSerializer(data=request.data)
#
#         if serializer.is_valid(raise_exception=True):
#             room_saved = serializer.save()
#             return Response({"Success": "Room '{}' created successfully.".format(room_saved.number)})
#         else:
#             return Response({"Error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)


def clients_in_room_form(request):
    rooms = Room.objects.all()
    return render(request, 'clients_in_room_form.html', {'rooms': rooms})


class ClientsInRoomView(APIView):
    def get(self, request, room_number, start_date, end_date):
        try:
            bookings = Bookings.objects.filter(
                room__number=room_number,
                check_in__range=[start_date, end_date],
                check_out__range=[start_date, end_date]
            )
            serializer = BookingSerializer(bookings, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"Error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


def clients_from_city_form(request):
    return render(request, 'clients_from_city_form.html')


class ClientsFromCityView(APIView):
    def get(self, request, city):
        try:
            clients = Client.objects.filter(from_city=city)
            serializer = ClientSerializer(clients, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"Error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


def cleaner_for_client_form(request):
    clients = Client.objects.all()
    return render(request, 'cleaner_for_client_form.html', {'clients': clients})


class CleanerInfoView(APIView):
    def get(self, request, client_id, work_day):
        try:
            client = Client.objects.get(id=client_id)
        except Client.DoesNotExist:
            return Response({"error": f"Client with id {client_id} does not exist"}, status=status.HTTP_404_NOT_FOUND)
        schedules = RoomCleaningSchedule.objects.filter(
            room__in=Room.objects.filter(
                bookings__user=client
            ),
            work_date__week_day=work_day
        ).distinct()

        serializer = EmployeeScheduleSerializer(schedules, many=True)
        return Response(serializer.data)


def free_rooms_for_date(request):

    return render(request, 'free_room_for_date.html')


class FreeRoomsAPIView(APIView):
    def get(self, request, check_in_date, check_out_date):
        try:
            check_in_date = datetime.strptime(check_in_date, '%Y-%m-%d').date()
            check_out_date = datetime.strptime(check_out_date, '%Y-%m-%d').date()

            all_rooms = Room.objects.all()

            booked_rooms = Bookings.objects.filter(
                check_in__lte=check_out_date,
                check_out__gte=check_in_date
            ).values_list('room_id', flat=True)

            free_rooms = all_rooms.exclude(id__in=booked_rooms)

            serializer = RoomSerializer(free_rooms, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"Error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


def clients_in_the_same_days(request):
    clients = Client.objects.all()
    return render(request, 'clients_in_same_days_form.html', {'clients': clients})


class ClientsInSameDaysView(APIView):
    def get(self, request, client_id, check_in_date, check_out_date):
        try:

            other_clients = Client.objects.exclude(id=client_id)

            bookings_in_same_days = Bookings.objects.filter(
                user__in=other_clients,
                check_in__lte=check_out_date,
                check_in__gte=check_in_date
            )

            serializer = BookingSerializer(bookings_in_same_days, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"Error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


class FireEmployeeView(generics.RetrieveDestroyAPIView):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    permission_classes = (IsAdminUser,)


def fire_employee(request):
    employees = Employee.objects.all()
    return render(request, 'fire_employee.html', {'employees': employees})


class UpdateEmployeeScheduleView(generics.RetrieveUpdateAPIView):
    queryset = EmployeeSchedule.objects.all()
    serializer_class = UpdateEmployeeScheduleSerializer
    permission_classes = (IsAdminUser,)


def update_employee_schedule(request):
    schedules = EmployeeSchedule.objects.all()
    return render(request, 'update_employee.html', {'schedules': schedules})


class CheckInClientView(generics.RetrieveUpdateAPIView):
    queryset = Bookings.objects.all()
    serializer_class = CheckInClientSerializer
    permission_classes = (IsAdminUser,)


def check_in_client(request):
    bookings = Bookings.objects.all()
    return render(request, 'check_in_client.html', {'bookings': bookings})


def quarterly_report(request):
    return render(request, 'quarterly_report.html')


class QuarterlyReportView(APIView):
    permission_classes = (IsAdminUser,)
    def get(self, request, quarter, year):
        try:
            start_date = f'{year}-{(quarter - 1) * 3 + 1}-01'
            end_date = f'{year}-{quarter * 3}-01'

            room_client_reports = Bookings.objects.filter(
                check_in__gte=start_date
            ).values('room__number').annotate(
                num_clients=Count('user')
            )

            floor_reports = Room.objects.values('floor').annotate(
                num_rooms=Count('id')
            )

            total_income_room = Bookings.objects.filter(
                check_in__gte=start_date
            ).values('room__number').annotate(
                total_income_for_room=Sum('room__cost')
            )

            total_income_hotel = Bookings.objects.filter(
                check_in__gte=start_date
            ).values('room__number').annotate(
                total_income_hotel=Coalesce(Sum('room__cost'), 0)
            ).aggregate(
                total_income_for_hotel=Sum('total_income_hotel')
            )['total_income_for_hotel']

            serializer = HotelReportSerializer({
                'room_client_reports': room_client_reports,
                'floor_reports': floor_reports,
                'total_income_for_room': total_income_room,
                'total_income_for_hotel': total_income_hotel,
            })

            return Response(serializer.data)
        except Exception as e:
            return Response({"Error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


def form_links(request):
    return render(request, 'form_links.html')


class UserBookingsView(ListAPIView):
    serializer_class = UserBookingsSerializer
    permission_classes = (IsAdminUser,)

    def get_queryset(self):
        user_id = self.kwargs['user_id']  # Assuming you pass the user_id in the URL
        return Client.objects.filter(id=user_id)


class RegisterView(APIView):
    def post(self, request):
        serializer = UserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)


class LoginView(APIView):
    def post(self, request):
        email = request.data['email']
        password = request.data['password']

        user = User.objects.filter(email=email).first()

        if user is None:
            raise AuthenticationFailed('User not found!')

        if not user.check_password(password):
            raise AuthenticationFailed('Incorrect password!')

        payload = {
            'id': user.id,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(days=14),
            'iat': datetime.datetime.utcnow()
        }

        token = jwt.encode(payload, 'secret', algorithm='HS256')

        response = Response()

        response.set_cookie(key='jwt', value=token, httponly=True)
        response.data = {
            'jwt': token
        }
        return response


class UserView(APIView):

    def get(self, request):

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/templates/check_in_client.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Links</title>
    <style>
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center; /* Center content horizontally */
            justify-content: center;
            height: 100vh;
        }

        h2, label {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            text-align: left;
            margin: 0;
            padding-left: 10px;
            width: auto; /* Allow the width to adjust to content */
        }

        select {
            font-family: Montserrat, sans-serif;
            padding: 10px;
            margin: 10px 0;
            width: auto;
            box-sizing: border-box;
            text-align: center;
        }

        input[type="button"] {
            font-family: Montserrat, sans-serif;
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #f4f4f4;
            text-decoration: none;
            border: 2px solid #fff;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px; /* Add margin to separate from select element */
        }

        input[type="button"]:hover {
            background-color: #555;
        }
    </style>
</head>

<body>

<h2>Check in and Check out</h2>
    <label for="booking">Select Client's booking:</label>
    <select name="schedule" id="booking" required>
        {% for booking in bookings %}
                <option value="{{ booking.id }}">{{ booking.user.first_name }} {{ booking.user.last_name }}'s booking
                    {{ booking.room }} from {{ booking.check_in }} to {{ booking.check_out }}</option>
        {% endfor %}
    </select>

    <input type="button" value="Select" onclick="submitForm()">
</form>
<script>
    function submitForm() {
        const bookingId = document.getElementById("booking").value;
        const url = `/hotel/check_in_client/${bookingId}/`;
        window.location.href = url;
    }
</script>
</body>

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/templates/cleaner_for_client_form.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cleaner for Client Form</title>
    <style>
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            color: #f4f4f4;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 80%;
            max-width: 400px; /* Set the maximum width for better readability */
            margin: 10px; /* Add margin for spacing */
        }

        label {
            text-align: left;
            margin: 10px 0; /* Add margin for spacing between labels */
        }

        select {
            font-family: Montserrat, sans-serif;
            padding: 10px;
            margin: 5px 0; /* Adjust margin for better spacing */
            width: auto;
            box-sizing: border-box;
        }

        input[type="submit"] {
            font-family: Montserrat, sans-serif;
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #f4f4f4;
            text-decoration: none;
            border: 2px solid #fff;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px; /* Add margin for spacing */
        }

        input[type="submit"]:hover {
            background-color: #555;
        }
    </style>
</head>
<body>

<h2>Cleaner for Client Form</h2>

<form method="get" id="cleanerForm" action="">
    <label for="client">Client:</label>
    <select name="client" id="client" required>
        {% for client in clients %}
            <option value="{{ client.id }}">{{ client.first_name }} {{ client.last_name }}</option>
        {% endfor %}
    </select>
    <br>

    <label for="work_day">Day of Week:</label>
    <select name="work_day" id="work_day" required>
        <option value="2">Monday</option>
        <option value="3">Tuesday</option>
        <option value="4">Wednesday</option>
        <option value="5">Thursday</option>
        <option value="6">Friday</option>
        <option value="7">Saturday</option>
        <option value="1">Sunday</option>
    </select>
    <br>

    <input type="submit" value="Get Cleaner">
</form>

<script>
    document.getElementById("cleanerForm").addEventListener("submit", function(event) {
        event.preventDefault(); // Prevent the form from submitting
        const clientId = document.getElementById("client").value;
        const workDay = document.getElementById("work_day").value;
        const url = `/hotel/cleaner_info/${clientId}/${workDay}/`;
        window.location.href = url;
    });
</script>

</body>
</html>

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/templates/clients_from_city_form.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Links</title>
    <style>
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center; /* Center the form horizontally within the available space */
            width: 80%;
            max-width: 400px; /* Set the maximum width for better readability */
            margin: 10px; /* Add margin for spacing */
        }

        label, h4 {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            text-align: left;
            margin: 10px 10px;
            padding-left: 0;
            margin-top: 10px; /* Add margin for spacing between labels */
        }

        select, input[type="date"] {
            font-family: Montserrat, sans-serif;
            padding: 10px;
            margin: 5px 0; /* Adjust margin for better spacing */
            width: auto;
            box-sizing: border-box;
            text-align: center;
        }

        button {
            font-family: Montserrat, sans-serif;
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #f4f4f4;
            text-decoration: none;
            border: 2px solid #fff;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px; /* Add margin for spacing */
        }

        button:hover {
            background-color: #555;
        }
    </style>
</head>
<body>

<form id="clientsFromCityForm">
    <h4 for="from_city">City:</h4>
    <input type="text" id="from_city" name="from_city" required>

    <button type="button" onclick="submitForm()">Submit</button>
</form>

<script>
    function submitForm() {
        const from_city = document.getElementById("from_city").value;
        const url = `/hotel/clients_from_city/${from_city}/`;
        window.location.href = url;
    }
</script>
</body>

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/templates/clients_in_room_form.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Links</title>
    <style>
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center; /* Center the form horizontally within the available space */
            width: 80%;
            max-width: 400px; /* Set the maximum width for better readability */
            margin: 10px; /* Add margin for spacing */
        }

        label {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            text-align: left;
            margin: 0;
            padding-left: 10px;
            margin-top: 10px; /* Add margin for spacing between labels */
        }

        select, input[type="date"] {
            font-family: Montserrat, sans-serif;
            padding: 10px;
            margin: 5px 0; /* Adjust margin for better spacing */
            width: auto;
            box-sizing: border-box;
            text-align: center;
        }

        button {
            font-family: Montserrat, sans-serif;
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #f4f4f4;
            text-decoration: none;
            border: 2px solid #fff;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px; /* Add margin for spacing */
        }

        button:hover {
            background-color: #555;
        }
    </style>
</head>
<body>

<form id="clientsInRoomForm">
    <label for="room">Room:</label>
    <select name="room" id="room" required>
        {% for room in rooms %}
            <option value="{{ room.number }}">{{ room.number }} {{ room.category }}</option>
        {% endfor %}
    </select>

    <label for="startDate">Start Date:</label>
    <input type="date" id="startDate" name="startDate" required>

    <label for="endDate">End Date:</label>
    <input type="date" id="endDate" name="endDate" required>

    <button type="button" onclick="submitForm()">Submit</button>
</form>

<script>
    function submitForm() {
        const roomNumber = document.getElementById("room").value;
        const startDate = document.getElementById("startDate").value;
        const endDate = document.getElementById("endDate").value;

        const url = `/hotel/clients_in_room/${roomNumber}/${startDate}/${endDate}`;
        window.location.href = url;
    }
</script>

</body>

students/k33421/Afonina_Natalia/Lab_3/lab_3/hotel/templates/form_links.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Links</title>
    <style>
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            margin: 0;
            justify-content: center;
            height: 100vh;
        }

        h2 {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            text-align: left;
            margin: 0px 20px;
        }

        li {
            list-style: none;
            margin: 10px 0;
            text-align: center;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #f4f4f4;
            text-decoration: none;
            border: 2px solid #fff; /* Обводка вокруг ссылок */
            border-radius: 5px;
            text-align: center;
        }

        a:hover {
            background-color: #555;
        }
        .hotel-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            opacity: 0.2;
        }
    </style>
</head>
<body>

    <h2>Links</h2>

    <ul>
        <li><a href="{% url 'hotel:room_list' %}">Room List</a></li>
        <li><a href="{% url 'hotel:client_list' %}">Client List</a></li>
        <li><a href="{% url 'hotel:create_room' %}">Create Room and Room List</a></li>

        <li><a href="{% url 'hotel:clients_in_room_form' %}">Clients in Room Form</a></li>
        <li><a href="{% url 'hotel:clients_from_city_form' %}">Clients from City Form</a></li>
        <li><a href="{% url 'hotel:cleaner_for_client_form' %}">Cleaner for Client Form</a></li>
        <li><a href="{% url 'hotel:free_rooms_form' %}">Free Rooms Form</a></li>
        <li><a href="{% url 'hotel:clients_in_the_same_days_form' %}">Clients in the same days form</a></li>


        <li><a href="{% url 'hotel:employee_list' %}">Hire Employee</a></li>
        <li><a href="{% url 'hotel:fire_employee' %}">Select Employee to Fire</a></li>
        <li><a href="{% url 'hotel:update_employee_schedule_form' %}">Update Employee Schedule</a></li>

        <li><a href="{% url 'hotel:check_in' %}">Check In or Check Out</a></li>


        <li><a href="{% url 'hotel:quarterly_report_data' %}">Quarterly Report Form</a></li>

    </ul>
</body>
</html>