students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/urls.py
from django.urls import path
from .views import RoomListView, BookingsListView, RoomDetailView, CancelBookingView, EditBookingView, IndexView
from . import views
from allauth.account.views import LoginView, LogoutView, SignupForm

app_name = 'hotel'

urlpatterns = [
    path('', views.IndexView, name='IndexView'),
    path('room_list/', views.RoomListView, name='RoomListView'),
    path('bookings_list/', views.BookingsListView.as_view(), name='BookingsListView'),
    path('room/<category>', views.RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking/cancel/<pk>', views.CancelBookingView.as_view(), name='CancelBookingView'),
    path('edit_booking/<pk>/', views.EditBookingView.as_view(), name='EditBookingView'),
    path('reviews/', views.review_list, name='review_list'),
    path('add_review/', views.AddReviewView.as_view(), name='add_review'),
    path('accounts/login/', LoginView.as_view(), name='account_login'),
    path('accounts/logout/', LogoutView.as_view(), name='account_logout'),
    path('home/', views.HomeView, name='HomeView')


]

students/k33421/Afonina_Natalia/Lab_2/lab_2/lab_2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lab_2 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import PermissionDenied
from django.db import models
from django.urls import reverse, reverse_lazy


class Hotel(models.Model):
    name = models.CharField(max_length=50)
    owner = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('SINGLE', 'Single Room'),
        ('DOUBLE', 'Double Room'),
        ('FAMILY', 'Family Room'),
        ('DELUXE', 'Deluxe Room'),
        ('SUITE', 'Suite'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=6, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    amenities = models.TextField()
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.number} {self.category} room'


class Bookings(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'

    def get_room_category(self):
        room_categories = dict(self.room.ROOM_CATEGORIES)
        room_category = room_categories.get(self.room.category)
        return room_category

    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

    def edit_booking(self):
        return reverse_lazy('hotel:EditBookingView', args=[self.pk, ])

    def create_review(self, rating, text):
        review = Review.objects.create(user=self.user, room=self.room, rating=rating, text=text)
        return review


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(default=5, choices=[(i, i) for i in range(1, 11)])
    text = models.TextField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    booking = models.ForeignKey(Bookings, on_delete=models.CASCADE)

    def __str__(self):
        return f'Review by {self.user} for {self.room}'


class Confirmation(models.Model):
    booking = models.OneToOneField(Bookings, on_delete=models.CASCADE)
    is_confirmed = models.BooleanField(default=False)
    confirmed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    confirmation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Confirmation for {self.booking} by {self.confirmed_by}'
    def save(self, *args, **kwargs):
        if self.confirmed_by and not self.confirmed_by.is_staff:
            raise PermissionDenied("Only staff members can confirm bookings.")
        super(Confirmation, self).save(*args, **kwargs)


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20, blank=True)
    birth_date = models.DateField(blank=True, null=True)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/forms.py
from allauth.account.forms import SignupForm
from django import forms

from hotel.models import Bookings, Review, Room


class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])


class EditBookingForm(forms.ModelForm):
    class Meta:
        model = Bookings
        fields = ['room', 'check_in', 'check_out']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'text', 'room', 'booking']


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
    birth_date = forms.DateField(label='Birth Date', required=False)

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.birth_date = self.cleaned_data['birth_date']
        user.save()
        return user

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/views.py
from allauth.account.views import LoginView, SignupView
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, FormView, View, DeleteView, UpdateView
from .models import Room, Bookings, Review, Confirmation, Hotel
from .forms import AvailabilityForm, EditBookingForm, ReviewForm
from hotel.booking_functions.availability import check_availability
from hotel.booking_functions.get_room_cat_url_list import get_room_cat_url_list


def RoomListView(request):
    room_category_url_list = get_room_cat_url_list()

    context = {
        "room_list": get_room_cat_url_list
    }
    return render(request, 'room_list_view.html', context)


class BookingsListView(ListView):
    model = Bookings

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Bookings.objects.all()
            return booking_list
        else:
            booking_list = Bookings.objects.filter(user=self.request.user)
            return booking_list


class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=category)
        if len(room_list) > 0:
            room = room_list[0]
            room_category = dict(room.ROOM_CATEGORIES).get(room.category, None)
            context = {
                'room_category': room_category,
                'form': form,
                'room_amenities': room.amenities,
                'room_price': room.cost
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            available_rooms = []
            for room in room_list:
                if check_availability(room, data['check_in'], data['check_out']):
                    if data['check_in'] < data['check_out']:
                        if data['check_in'] > timezone.now():
                            available_rooms.append(room)
                        else:
                            messages.error(request, "You can't book a room for dates in the past.")
                            return redirect('hotel:RoomListView')
                    else:
                        messages.error(request, "You can't book a room with check out earlier than check in.")
                        return redirect('hotel:RoomListView')
                else:
                    messages.error(request, "Room is fully booked for the selected dates.")
                    return redirect('hotel:RoomListView')
            if len(available_rooms) > 0:
                room = available_rooms[0]
                booking = Bookings.objects.create(
                    user=self.request.user,
                    room=room,
                    check_in=data['check_in'],
                    check_out=data['check_out']
                )
                booking.save()
                confirmation = Confirmation.objects.create(
                    booking=booking,
                    is_confirmed=False,
                    confirmed_by=None
                )
                confirmation.save()
                messages.success(request, 'Your booking created')
                return redirect('hotel:RoomListView')
            else:
                messages.error(request, 'This category of rooms is fully booked. Try another one')
                return redirect('hotel:RoomListView')


class CancelBookingView(DeleteView):
    model = Bookings
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('hotel:BookingsListView')


class EditBookingView(UpdateView):
    model = Bookings
    form_class = EditBookingForm
    template_name = 'edit_booking.html'
    success_url = reverse_lazy('hotel:BookingsListView')

    def form_valid(self, form):
        if form.has_changed():
            data = form.cleaned_data
            room = data['room']
            if check_availability(room, data['check_in'], data['check_out']):
                if data['check_in'] > timezone.now():
                    form.save()
                    messages.success(self.request, 'Your booking has been updated')
                    return redirect(self.success_url)
                else:
                    messages.error(self.request, "You can't book a room for dates in the past.")
                    return redirect('hotel:BookingsListView')
            else:
                messages.error(self.request, 'This room is fully booked for the selected dates. Try another one')
                return redirect('hotel:BookingsListView')
        else:
            messages.info(self.request, 'No changes were made')
            return redirect('hotel:BookingsListView')


def review_list(request):
    reviews = Review.objects.all()
    return render(request, 'hotel/review_list.html', {'reviews': reviews})


class AddReviewView(View):
    template_name = 'hotel/add_review.html'

    def get(self, request):
        form = ReviewForm()
        if self.request.user.is_staff:
            return render(request, self.template_name, {'form': form})
        else:
            bookings = Bookings.objects.filter(user=self.request.user, confirmation__is_confirmed=True)
            form.fields['booking'].queryset = bookings
            room_ids = [booking.room.id for booking in bookings]
            form.fields['room'].queryset = Room.objects.filter(id__in=room_ids)

            return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ReviewForm(request.POST)
        user = self.request.user

        if form.is_valid():
            booking_id = form.cleaned_data['booking'].id
            room_id = form.cleaned_data['room'].id
            rating = form.cleaned_data['rating']
            text = form.cleaned_data['text']

            if user.is_staff:
                review = Review.objects.create(user=user, booking_id=booking_id, room_id=room_id, rating=rating,
                                               text=text)
                review.save()
            else:
                bookings = Bookings.objects.filter(user=user)
                form.fields['booking'].queryset = bookings
                room_ids = [booking.room.id for booking in bookings]
                form.fields['room'].queryset = Room.objects.filter(id__in=room_ids)

                # Check if the form is valid again after updating querysets
                if form.is_valid():
                    review = Review.objects.create(user=user, booking_id=booking_id, room_id=room_id, rating=rating,
                                                   text=text)
                    review.save()
            return redirect('hotel:review_list')
        else:
            return redirect('hotel:review_list')


def IndexView(request):
    hotel_info = Hotel.objects.first()
    context = {
        "hotel_info": hotel_info
    }
    return render(request, 'index.html', context)


def HomeView(request):
    return render(request, 'home.html')

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/templates/booking_cancel_view.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cancel Booking</title>

    <style>
        /* Ваши стили */
        /* Стили для общей страницы */
        body {
            font-family: Montserrat, sans-serif;
            color: #333;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .room {
            font-family: Montserrat, sans-serif;
            color: #333;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 60%;
            margin: 20px auto; /* Центрирование по горизонтали */
            padding: 20px;
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        /* Стили для изображения комнаты */
        .room img {
            width: 100%; /* Заполнение изображения внутри блока .room */
            max-height: 300px; /* Ограничение максимальной высоты изображения */
            border-radius: 5px;
        }

        /* Стили для кнопки "Cancel the Booking" */
        #booking-form button {
            font-family: Montserrat, sans-serif;
            padding: 10px 20px;
            background-color: #333;
            color: #fff;
            border: 2px solid #fff;
            border-radius: 5px;
            text-decoration: none;
            text-align: center;
            cursor: pointer;
            margin-top: 20px;
        }

        #booking-form button:hover {
            background-color: #555;
        }

        /* Стили для кнопки Home */
        .home {
            font-family: Montserrat, sans-serif;
            position: absolute;
            top: 10px;
            left: 10px;
            z-index: 999;
        }

        .home a {
            font-family: Montserrat, sans-serif;
            color: #fff;
            background-color: #333;
            padding: 10px 20px;
            border: 2px solid #fff;
            border-radius: 5px;
            text-decoration: none;
            display: inline-block;
            margin-right: 10px; /* Добавьте отступ справа, например, 10px */
        }

        .home a:hover {
            background-color: #555;
        }
    </style>

</head>

<body>

    <!-- Div 1: Back to Home -->
        <div class="home">
            <a href="{% url 'hotel:BookingsListView' %}">Get Back</a>
        </div>
    <!-- Main Content -->
    <div class="content">

        <!-- Room Details -->
        <div class="room">


            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{bookings.get_room_category}}</h1>
                {% if bookings.get_room_category == "Single Room" %}
                    <img src="{% static 'single.png' %}" alt="{{bookings.get_room_category}}">
                {% elif bookings.get_room_category == "Double Room" %}
                    <img src="{% static 'double.png' %}" alt="{{bookings.get_room_category}}">
                {% elif bookings.get_room_category == "Deluxe Room" %}
                    <img src="{% static 'deluxe.png' %}" alt="{{bookings.get_room_category}}">
                {% elif bookings.get_room_category == "Family Room" %}
                    <img src="{% static 'family.png' %}" alt="{{bookings.get_room_category}}">
                {% elif bookings.get_room_category == "Suite" %}
                    <img src="{% static 'suite.png' %}" alt="{{bookings.get_room_category}}">
                {% endif %}
                <p> </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you want to cancel this booking: {{bookings.room.number}} {{bookings.get_room_category}} from {{bookings.check_in}} to {{bookings.check_out}}?</h2>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/templates/home.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <style>
        /* Общие стили для страницы */
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        /* Стили для заголовка */
        h2 {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            text-align: center;
        }

        /* Стили для меню-ссылок */
        li {
            list-style: none;
            margin: 10px 0;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #f4f4f4;
            text-decoration: none;
            border: 2px solid #fff; /* Обводка вокруг ссылок */
            border-radius: 5px;
            text-align: center;
        }

        a:hover {
            background-color: #555;
        }

        /* Стили для изображения */
        .hotel-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            z-index: -1; /* Помещаем изображение под основным контентом */
            opacity: 0.2; /* Устанавливаем прозрачность */
        }
        /* CSS для сообщений */
        .messages {
            position: fixed;
            top: 0;
            left: 50%;
            transform: translateX(-50%);
            max-width: 400px; /* Задайте желаемую максимальную ширину */
            background-color: #333;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            text-align: center;
            transition: top 0.3s ease;
            display: none; /* Начнем с скрытым блоком сообщений */
        }

        .messages.show {
            display: block; /* Показывает сообщения при добавлении класса "show" */
        }
    </style>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <img src="{% static 'img.png' %}" alt="Hotel Image" class="hotel-image">
    <h2>Welcome {{user.first_name}} {{user.last_name}}</h2>
    <li><a href="{% url 'hotel:RoomListView' %}">View Room List</a></li>
    <li><a href="{% url 'hotel:review_list' %}">Reviews</a></li>
    <li><a href="{% url 'hotel:add_review' %}">Add Review</a></li>
    <li><a href="{% url 'hotel:BookingsListView' %}">Manage Bookings</a></li>
    <li><a href="{% url 'account_logout' %}">Log out</a></li>

    <script>
        // JavaScript код
        document.addEventListener('DOMContentLoaded', function() {
            const messages = document.querySelector('.messages');

            // Показать сообщения
            function showMessages() {
                messages.classList.add('show');
            }

            // Скрыть сообщения
            function hideMessages() {
                messages.classList.remove('show');
            }

            // Показать сообщения при загрузке страницы (если они есть)
            if (messages) {
                showMessages();

                // Закрыть сообщения через некоторое время (например, через 5 секунд)
                setTimeout(hideMessages, 5000);
            }
        });
    </script>
</body>
</html>

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/templates/index.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Natasha's Hotel</title>
    <style>
        /* Общие стили для страницы */
        body {
            font-family: Montserrat, sans-serif;
            background-color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }


        /* Стили для заголовка */
        h1 {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            text-align: center;

        }

        /* Стили для описания */
        p {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;;
            text-align: center;
            max-width: 80%; /* Установите желаемую максимальную ширину для текста */
            margin: 0 auto; /* Чтобы выровнять текст по центру */
        }

        /* Стили для меню-ссылки */
        .menu-link {
            font-family: Montserrat, sans-serif;
            color: #f4f4f4;
            background-color: #333;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            text-align: center;
            display: inline-block;
            margin-top: 20px;
            border: 2px solid #fff;
        }

        /* Стили для изображения */
        .hotel-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            z-index: -1; /* Помещаем изображение под основным контентом */
            opacity: 0.2; /* Устанавливаем прозрачность */
        }
    </style>
</head>
<body>
    <img src="{% static 'img.png' %}" alt="Hotel Image" class="hotel-image">
    <h1>{{ hotel_info.name }}</h1>
    <p>{{ hotel_info.description }}</p>
    <a href="{% url 'account_login' %}" class="menu-link">Log in to explore our rooms and reviews</a>
</body>
</html>

students/k33421/Afonina_Natalia/Lab_2/lab_2/hotel/templates/room_list_view.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Natasha's Hotel</title>
    <style>
        /* Общие стили для страницы */
        body {
            font-family: Montserrat, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        /* Стили для заголовка */
        #brand {
            font-family: Montserrat, sans-serif;
            color: #333;
            text-align: center;
        }

        /* Стили для внутреннего содержания */
        /* Стили для кнопки Home */
        .home {
            font-family: Montserrat, sans-serif;
            position: absolute;
            top: 10px;
            left: 10px;
            z-index: 999;
        }

        .home a {
            font-family: Montserrat, sans-serif;
            color: #fff;
            background-color: #333;
            padding: 10px 20px;
            border: 2px solid #fff;
            border-radius: 5px;
            text-decoration: none;
        }

        .home a:hover {
            background-color: #555;
        }

        .content {
            font-family: Montserrat, sans-serif;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        /* Стили для комнат */
        .room {
            font-family: Montserrat, sans-serif;
            margin: 20px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            text-align: center;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 18%; /* Устанавливаем ширину комнаты */
            float: left; /* Выравниваем комнаты влево */
        }

        .room a {
            font-family: Montserrat, sans-serif;
            color: #333;
            text-decoration: none;
        }

        /* Стили для заголовка комнаты */
        .room h2 {
            font-family: Montserrat, sans-serif;
            font-size: 24px;
        }

        /* Стили для изображения комнаты */
        .room img {
            width: 100%; /* Заполнение изображения внутри блока .room */
            max-height: 120px; /* Ограничение максимальной высоты изображения */
            border-radius: 5px;
        }
        /* CSS для сообщений */
        .messages {
            position: fixed;
            top: 0;
            left: 50%;
            transform: translateX(-50%);
            max-width: 400px; /* Задайте желаемую максимальную ширину */
            background-color: #333;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            text-align: center;
            transition: top 0.3s ease;
            display: none; /* Начнем с скрытым блоком сообщений */
        }

        .messages.show {
            display: block; /* Показывает сообщения при добавлении класса "show" */
        }
    </style>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- Brand -->
    <h1 id="brand">Natasha's Hotel</h1>

    <!-- Main Content -->
    <div class="home">
                <!-- Div 1: Back to Home -->
        <div class="home">
            <a href="{% url 'hotel:HomeView' %}">Home</a>
        </div>

    </div>
    <div class="content">
        {% for room_category, room_url in room_list %}
        <div class="room">
            <a href="{{room_url}}">
                <h2>{{room_category}}</h2>
                {% if room_category == "Single Room" %}
                    <img src="{% static 'single.png' %}" alt="{{room_category}}">
                {% elif room_category == "Double Room" %}
                    <img src="{% static 'double.png' %}" alt="{{room_category}}">
                {% elif room_category == "Deluxe Room" %}
                    <img src="{% static 'deluxe.png' %}" alt="{{room_category}}">
                {% elif room_category == "Family Room" %}
                    <img src="{% static 'family.png' %}" alt="{{room_category}}">
                {% elif room_category == "Suite" %}
                    <img src="{% static 'suite.png' %}" alt="{{room_category}}">
                {% endif %}
            </a>
        </div>
        {% endfor %}
    </div>

    <script>
        // JavaScript код
        document.addEventListener('DOMContentLoaded', function() {
            const messages = document.querySelector('.messages');

            // Показать сообщения
            function showMessages() {
                messages.classList.add('show');
            }

            // Скрыть сообщения
            function hideMessages() {
                messages.classList.remove('show');
            }

            // Показать сообщения при загрузке страницы (если они есть)
            if (messages) {
                showMessages();

                // Закрыть сообщения через некоторое время (например, через 5 секунд)
                setTimeout(hideMessages, 5000);
            }
        });
    </script>
</body>
</html>